version: '3.8'

services:
  couchdb:
    image: couchdb:3.3.3
    container_name: obsidian_couchdb
    ports:
      # 将 VPS 的 80 端口映射到容器的 5984 端口
      # 这样 Cloudflare 才能正常通过 http 协议回源
      - "80:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ./data:/opt/couchdb/data
      # 引用 local.ini 自动开启 CORS，省去手动配置
      - ./local.ini:/opt/couchdb/etc/local.d/10-custom.ini
    restart: always
